obj-y += axp-mfd.o

#Make this built-in, so that it will be loaded before I2C driver

obj-$(CONFIG_AXP_PMU) += axp-board.o
obj-$(CONFIG_AXP_PMU) += axp-regu.o
obj-$(CONFIG_AXP_PMU) += axp-sply.o
#obj-$(CONFIG_AXP_PMU) += axp-gpio.o

